version: '3'
services:
  postgres_db24:
    image: postgres:14-alpine
    container_name: "postgres24"
    environment:
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=luis_barrondb"
      - "POSTGRES_USER=luis_barron"
    ports:
      - "10024:5524"
    volumes:
      - "/home/luis_barron/postgres:/usr/src/postgres"
    networks:
      - our-library-net
    command: -p 5524

  web24:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && pytest && python manage.py runserver 0.0.0.0:8024"
    container_name: "django24"
    depends_on: 
      - postgres_db24
    environment:
      - "PSQL_DBNAME=luis_barrondb"
      - "PSQL_USERNAME=luis_barron"
      - "PSQL_PASS=admin"
      - "PSQL_HOST=172.24.0.10" # You must use the previous command in order to get this HOST172.24.0.20
      - "PSQL_PORT=5524"
    volumes:
    # "RUTA/DEL/SERVIDOR:RUTA/DENTRO/DEL/CONTENEDOR"
      - "/home/luis_barron/Django-REST-Exercise:/usr/src/django/library"
    ports:
      - "9024:8024"
    networks:
      - our-library-net

networks:
  our-library-net:
    external: true
    driver: bridge